plugins {
    id 'com.android.application'
}

android {
    namespace 'com.januprime.autoreply'
    compileSdk 34

    defaultConfig {
        applicationId "com.januprime.autoreply"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    // ఇక్కడే మనకు కావాల్సిన లైబ్రరీస్ యాడ్ చేస్తాం
}
